# Generated by Django 3.0.8 on 2020-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comments_items_useritems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='useritems',
            options={'verbose_name_plural': 'User Items'},
        ),
        migrations.AlterField(
            model_name='items',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
