# Generated by Django 3.0.8 on 2020-07-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200710_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritems',
            old_name='userItem',
            new_name='Item',
        ),
    ]
