# Generated by Django 3.0.8 on 2020-07-11 10:43

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200710_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(auctions.models.Category), to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
