# Generated by Django 3.0.8 on 2020-07-11 17:52

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200711_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(auctions.models.Category), related_name='categoryItems', to='auctions.Category'),
        ),
    ]
