# Generated by Django 3.0.8 on 2020-07-11 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200711_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
