# Generated by Django 3.0.8 on 2020-07-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200712_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidOwner',
            new_name='bid_creator',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='owner',
            new_name='item_owner',
        ),
        migrations.RenameField(
            model_name='useritems',
            old_name='Item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='useritems',
            old_name='user',
            new_name='user_id',
        ),
    ]
